"""initial

Revision ID: f23bd4148b28
Revises: 
Create Date: 2025-07-20 17:46:37.788902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23bd4148b28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('mac_address', sa.String(length=64), nullable=True),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.Column('hardware_version', sa.String(length=32), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    # ### end Alembic commands ###
